  cmake_minimum_required(VERSION 3.8)
  project(cable_robot_hardware)

  if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    add_compile_options(-Wall -Wextra -Wpedantic)
  endif()

  find_package(ament_cmake REQUIRED)
  find_package(rclcpp REQUIRED)
  find_package(hardware_interface REQUIRED)
  find_package(pluginlib REQUIRED)

  add_library(cable_robot_hardware SHARED
    src/cable_robot_hardware.cpp
  )

  target_include_directories(cable_robot_hardware PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
  )

  ament_target_dependencies(cable_robot_hardware
    rclcpp
    hardware_interface
    pluginlib
  )

  pluginlib_export_plugin_description_file(
    hardware_interface cable_robot_hardware.xml
  )

  install(TARGETS cable_robot_hardware
    EXPORT export_cable_robot_hardware
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION lib
    RUNTIME DESTINATION bin
  )

  install(DIRECTORY include/
    DESTINATION include
  )

  ament_export_include_directories(include)
  ament_export_libraries(cable_robot_hardware)
  ament_export_targets(export_cable_robot_hardware)

  ament_package()

